# Generated by Django 5.2 on 2025-05-10 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_ID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='管理员ID')),
                ('admin_name', models.CharField(max_length=50, verbose_name='管理员姓名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
            ],
            options={
                'verbose_name': '管理员表',
                'verbose_name_plural': '管理员表',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名')),
            ],
            options={
                'verbose_name': '课程表',
                'verbose_name_plural': '课程表',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.CharField(max_length=100, verbose_name='学期名')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
            ],
            options={
                'verbose_name': '学期表',
                'verbose_name_plural': '学期表',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tea_ID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='教师工号')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='教师姓名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别')),
                ('education', models.CharField(blank=True, max_length=50, null=True, verbose_name='学历')),
                ('major', models.CharField(blank=True, max_length=50, null=True, verbose_name='专业')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='入校时间')),
                ('is_working', models.BooleanField(default=True, verbose_name='是否在职')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=100, verbose_name='考试类别名')),
                ('start_date', models.DateField(verbose_name='考试开始日期')),
                ('end_date', models.DateField(verbose_name='考试结束日期')),
                ('is_lock', models.BooleanField(default=False, verbose_name='是否锁定')),
                ('sem_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwc_app.semester', verbose_name='学期')),
            ],
            options={
                'verbose_name': '考试类别表',
                'verbose_name_plural': '考试类别表',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_num', models.SmallIntegerField(choices=[(7, '七年级'), (8, '八年级'), (9, '九年级')], verbose_name='年级')),
                ('clas_num', models.SmallIntegerField(verbose_name='班级')),
                ('class_name', models.CharField(max_length=50, verbose_name='班级名')),
                ('sem_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwc_app.semester', verbose_name='学期')),
                ('headteacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwc_app.teacher', verbose_name='班主任ID')),
            ],
            options={
                'verbose_name': '班级表',
                'verbose_name_plural': '班级表',
                'unique_together': {('grade_num', 'clas_num', 'sem_ID')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_ID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学生学号')),
                ('student_name', models.CharField(max_length=50, verbose_name='学生姓名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='入学年月')),
                ('is_studying', models.BooleanField(default=True, verbose_name='是否在校')),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jwc_app.classes', verbose_name='当前班级')),
            ],
            options={
                'verbose_name': '学生表',
                'verbose_name_plural': '学生表',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='成绩')),
                ('cla_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jwc_app.classes', verbose_name='班级')),
                ('cou_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwc_app.course', verbose_name='课程')),
                ('exam_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwc_app.exam', verbose_name='考试类别')),
                ('stu_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwc_app.student', verbose_name='学生学号')),
            ],
            options={
                'verbose_name': '学生成绩表',
                'verbose_name_plural': '学生成绩表',
                'unique_together': {('stu_ID', 'exam_ID', 'cou_ID')},
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwc_app.classes', verbose_name='班级')),
                ('cou_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwc_app.course', verbose_name='课程')),
                ('tea_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwc_app.teacher', verbose_name='教师工号')),
            ],
            options={
                'verbose_name': '教师任课表',
                'verbose_name_plural': '教师任课表',
                'unique_together': {('tea_ID', 'cla_ID', 'cou_ID')},
            },
        ),
    ]
